rm -f *.txt *.bin

# Copyright (C) 2018 Jose Marco de la Rosa
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo "*** Generating the source .txt ref data file"
#for f in *.bin; do echo "Processing $f file.."; done

./generate_test_data_txt_file.py 7 0.5 ref > /dev/null

printf "\n*** Applying the c-implemented filter to the ref txt files\n"
for f in ref_*.txt
do
	for t in float double
	do
		printf "%s %s\n" ../../build/test_S_filter_apply_to_reference_file_$t $f
		../../build/test_S_filter_apply_to_reference_file_$t $f > /dev/null
	done
done

printf "\n*** Applying the python scipy filter to the binary files generated in the previous step\n"
for f in ref_*norm_coefs_S_applyed_*.bin
do
	printf "%s %s\n" ./test_apply_scipy_filter_to_binary.py $f
	./test_apply_scipy_filter_to_binary.py $f > /dev/null
done

printf "\n*** Testing c-implemented files with the binary files generated in the previous step\n"
for t in float double
do
	for f in ref_*norm_coefs_S_applyed_${t}_scipy.bin
	do
		printf "%s %s\n" ../../build/test_S_filter_with_reference_binary_$t $f
		../../build/test_S_filter_with_reference_binary_$t $f > /dev/null
	done
done

printf "\n*** Testing c filters output binary files generated in the previous step with python scipy filter\n"
for t in float double
do
	for f in ref_*norm_coefs_S_applyed_${t}_scipy_out_${t}.bin
	do
		printf "%s %s\n" ./test_S_filter_correct_scipy.py $f
		./test_S_filter_correct_scipy.py $f > /dev/null
	done
done

printf "\nRenaming the files to something shorter\n"
rename ref_ binary_ref_data_ *scipy.bin
rename _S_applyed "" *scipy.bin
rename ref_ text_ref_data_ *coefs.txt

printf "\nCopying the files generated by the python scipy filter to the tests folder for later testing\n"
cp binary_ref_data_* ..
cp text_ref_data_* ..
